# ./.tmuxinator.yml

name: chumcheck
root: ~/Code/chumcheck/

windows:
  - editor: nvim
  - term:
  - server: cd backend && npm run dev
  - frontend: cd frontend && BROWSER=google-chrome-stable pnpm dev --open
